### ISSUE TITLE
Arithmetic operation resulted in an overflow

### ISSUE THREAD

**Issue by thgiang** [Akaion/Jupiter#1]
Please help me with this error:
Arithmetic operation resulted in an overflow

` IntPtr baseAddress = new IntPtr(0x30000000);`
`var vddr = memoryModule.PatternScan(gameProcess.Id, baseAddress, "00 00 80 3F 00 00 80 3F 00 00 80 3F 00 00 80 3F 00 00 00 00 00 00 00 00 00 00 80 3F 00 00 00 00 00 00 00 00 00 00 80 3F");`

**Comment by Akaion** [comment]
Thanks for the bug report. Could you provide me with some more info? Are you looing for a pattern in an x86 or x64 process?

**Comment by Akaion** [comment]
I think I know the problem so I will do some testing  and hopefully have a fix when I get home from work

**Comment by Akaion** [comment]
@thgiang I'm currently unable to replicate you're issue in both x86 and x64. I however add a check in to the pattern scanner to hopefully solve any arithmetic overflow exceptions from happening.

I would reccomend you reduce the size of your pattern (if possible as it seems to be causing some performance issues for me.)

Also I used the following code to find to successfully find any pattern I provided (maybe try this)

```csharp
using System.Diagnostics;
using Jupiter;

// Get an instance of the process

var process = Process.GetProcessesByName("TestProcess")[0];

// Initialize a test array to write into memory

var testArray = new byte[] {0x54, 0x01, 0x4A, 0xAA, 0xFF, 0xFF, 0xFF, 0xFF, 0x6A};

// Allocate memory for the test array in memory

var testArrayAddress = memoryModule.AllocateMemory("TestProcess", testArray.Length);

// Write the test array into memory

memoryModule.WriteMemory("TestProcess", testArrayAddress, testArray);

// Scan for the pattern

var patternAddress = memoryModule.PatternScan("TestProcess", process.MainModule.BaseAddress, "54 ?? 4A AA FF FF FF ?? 6A");

if (testArrayAddress  == patternAddress)
{
    Console.WriteLine("Found pattern");
}
```

**Comment by vadbut** [comment]
It appears I have an identical issue:
I try to search for a pattern in a 32-bit application. I compiled Jupiter and my app in 32 bit (x86).
I tried different pattern lengths and I get an "arithmetic operation resulted in an overflow" even for a pattern consisting of six symbols.
`MemoryModule m = new Jupiter.MemoryModule(process_id);
var x = m.PatternScan("A1 ?? ?? ?? ?? 85");`
How can I debug this?
