### ISSUE TITLE
Why not use the struct constraint for <TStructure> generic methods

### ISSUE THREAD

**Issue by Happypig375** [Akaion/Jupiter#2]
Is there a reason to not use the `where TStructure : struct`? Checking with reflection (`typeof(TStructure).IsValueType`) seems to time-consuming and unchecked by the compiler.

**Comment by Happypig375** [comment]
Write should be separated into 2 overloads, one for structs, one for string. This ensures minimal runtime exceptions.

**Comment by Akaion** [comment]
This actually sounds like a really good idea. I'll take a look at later thanks for the advice :D
